version: "3"
services:
    
    
    vote:
        image: adityagaddhyan/voting-app
        ports: 
            - "3000:3000"
        depends_on:
            - redis
        networks:
            - front-end
            - back-end
        volumes: 
            - ./vote:/app
    result:
        image: adityagaddhyan/voting-result
        ports: 
            - "3011:3011"
        depends_on:
            - mongodb
        networks: 
            - back-end
            - front-end
        volumes: 
            - ./result:/app

    worker:
        image: adityagaddhyan/service-worker
        depends_on: 
            - redis
            - mongodb
        networks: 
            - back-end
        volumes: 
            - ./worker:/app
    redis:
        image : redis
        command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379","&&","sudo", "systemctl", "restart", "redis"]
        ports: 
            - "6379:6379"
        networks: 
            - back-end
        volumes: 
            - ./redis:/app
    mongodb:
        image: mongo
        ports:
            - "27017:27017"
        volumes: 
            - ./db:/app
    
volumes:
    db-data:
    
networks:
    front-end:
    back-end:

        

            