version: "3"
services:
    redis:
        image: redis
    mongo:
        image: mongo
    vote:
        build: ./voting/
        ports:
            - "4000:3000"
        links:
            - redis
    result:
        build: ./result
        ports:
            - "3011:3011"
        links:
            - mongo
    worker:
        build: ./service worker
        links:
            - redis
            - mongo
